# Generated by Django 3.1.5 on 2021-07-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=models.CharField(max_length=9),
        ),
    ]
